
package common.config.xmlres.server
{   
	public class DBModel
	{
		public static var Npc:Pub_NpcResModel
public static var Role_Property:Pub_Role_PropertyResModel
public static var Model:Pub_ModelResModel
public static var Shop_Normal:Pub_Shop_NormalResModel
public static var Shop_Page:Pub_Shop_PageResModel
public static var Npc_Talk:Pub_Npc_TalkResModel
public static var Sitzup_Up:Pub_Sitzup_UpResModel
public static var Shout_Content:Pub_Shout_ContentResModel
public static var Npc_Shout:Pub_Npc_ShoutResModel
public static var Npc_Block:Pub_Npc_BlockResModel
public static var Uptarget:Pub_UptargetResModel
public static var Spa_Msg:Pub_Spa_MsgResModel
public static var Tools:Pub_ToolsResModel
public static var Equip_Suit:Pub_Equip_SuitResModel
public static var Compose:Pub_ComposeResModel
public static var Equip_Strong_2:Pub_Equip_Strong_2ResModel
public static var Map:Pub_MapResModel
public static var Map_Spawn_Client:Pub_Map_Spawn_ClientResModel
public static var Seek:Pub_SeekResModel
public static var Send:Pub_SendResModel
public static var Map_Seek:Pub_Map_SeekResModel
public static var Map_Send:Pub_Map_SendResModel
public static var Map_Zones:Pub_Map_ZonesResModel
public static var Instance:Pub_InstanceResModel
public static var Drop:Pub_DropResModel
public static var Skill:Pub_SkillResModel
public static var Skill_Buff:Pub_Skill_BuffResModel
public static var Skill_Data:Pub_Skill_DataResModel
public static var Skill_Special:Pub_Skill_SpecialResModel
public static var Family:Pub_FamilyResModel
public static var Task:Pub_TaskResModel
public static var Task_Step:Pub_Task_StepResModel
public static var Task_Prize:Pub_Task_PrizeResModel
public static var Limit_Times:Pub_Limit_TimesResModel
public static var HeadIcon:Pub_HeadIconResModel
public static var Exp:Pub_ExpResModel
public static var Camp:Pub_CampResModel
public static var Kingname:Pub_KingnameResModel
public static var Hint:Pub_HintResModel
public static var Vip:Pub_VipResModel
public static var Achievement:Pub_AchievementResModel
public static var Action_Desc:Pub_Action_DescResModel
public static var Underwrite_Type:Pub_Underwrite_TypeResModel
public static var Theme:Pub_ThemeResModel
public static var Title:Pub_TitleResModel
public static var Awoke:Pub_AwokeResModel
public static var Online_Prize:Pub_Online_PrizeResModel
public static var Interface_Clew:Pub_Interface_ClewResModel
public static var Variable:Pub_VariableResModel
public static var Manage_Action:Pub_Manage_ActionResModel
public static var Change:Pub_ChangeResModel
public static var Book:Pub_BookResModel
public static var Sweep:Pub_SweepResModel
public static var Top_Prize:Pub_Top_PrizeResModel
public static var Action_Start:Pub_Action_StartResModel
public static var Commend:Pub_CommendResModel
public static var QQShare:Pub_QQShareResModel
public static var Convoy:Pub_ConvoyResModel
public static var UpDate:Pub_UpDateResModel
public static var Enter_Prize:Pub_Enter_PrizeResModel
public static var Action_Pay:Pub_Action_PayResModel
public static var Config:Pub_ConfigResModel
public static var Tool_Attr:Pub_Tool_AttrResModel
public static var Yellow:Pub_YellowResModel
public static var Sys_Effect:Pub_Sys_EffectResModel
public static var Bourn_Star:Pub_Bourn_StarResModel
public static var Sitzup_Show:Pub_Sitzup_ShowResModel
public static var Task_Award_Config:Pub_Task_Award_ConfigResModel
public static var Vip_Type:Pub_Vip_TypeResModel
public static var Sound:Pub_SoundResModel
public static var Effect_Sound:Pub_Effect_SoundResModel
public static var Shop_Ib:Pub_Shop_IbResModel
public static var Equip_Resolve:Pub_Equip_ResolveResModel
public static var Action_Fore:Pub_Action_ForeResModel
public static var Ibshop_Page:Pub_Ibshop_PageResModel
public static var QQInviteFriend:Pub_QQInviteFriendResModel
public static var Pack_Open:Pub_Pack_OpenResModel
public static var Vip_Prompt:Pub_Vip_PromptResModel
public static var Equip_Strong_Cost:Pub_Equip_Strong_CostResModel
public static var Action_Target:Pub_Action_TargetResModel
public static var Payment_Day:Pub_Payment_DayResModel
public static var Exploit:Pub_ExploitResModel
public static var Soar:Pub_SoarResModel
public static var Sitzup_Name:Pub_Sitzup_NameResModel
public static var Vip_Level_Prize:Pub_Vip_Level_PrizeResModel
public static var Payment_Start:Pub_Payment_StartResModel
public static var Blade:Pub_BladeResModel
public static var Exp_Action_Prize:Pub_Exp_Action_PrizeResModel
public static var Combine:Pub_CombineResModel
public static var Marriage_Pack:Pub_Marriage_PackResModel
public static var Marriage_Beatitude:Pub_Marriage_BeatitudeResModel
public static var Hundred_Fight:Pub_Hundred_FightResModel
public static var BigTime:Pub_BigTimeResModel
public static var Dragon_Boat:Pub_Dragon_BoatResModel
public static var Gem:Pub_GemResModel
public static var Heaven:Pub_HeavenResModel
public static var God:Pub_GodResModel
public static var Wing:Pub_WingResModel
public static var Invest:Pub_InvestResModel
public static var Invest_Repay:Pub_Invest_RepayResModel

	}
}
