--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")
Scene:setLocalZOrder(0)

--Create Image_4
localLuaFile=require("LuaScript.image")
local Image_4=localLuaFile.CreateCustomNode()
Image_4:ignoreContentAdaptWithSize(false)
Image_4:loadTexture("image/scenebg.png",0)

Image_4:setFlippedX(false)
Image_4:setFlippedY(false)

Image_4:setScale9Enabled(false)
Image_4:setCapInsets(cc.rect(0,0,0,0))
Image_4:setTouchEnabled(false)
Image_4:setLayoutComponentEnabled(true)
Image_4:setName("Image_4")
Image_4:setLocalZOrder(0)
Image_4:setTag(17)
Image_4:setCascadeColorEnabled(true)
Image_4:setCascadeOpacityEnabled(true)
Image_4:setVisible(true)
Image_4:setAnchorPoint(0, 0)
Image_4:setPosition(0, 0)
Image_4:setScaleX(1)
Image_4:setScaleY(1)
Image_4:setRotation(0)
Image_4:setRotationSkewX(0)
Image_4:setRotationSkewY(0)
Image_4:setOpacity(255)
Image_4:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Image_4)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(1)
layout:setPercentHeight(1)

layout:setSize(cc.size(640, 960))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(0)
layout:setRightMargin(0)
layout:setTopMargin(0)
layout:setBottomMargin(0)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Scene:addChild(Image_4)

--Create TextField_user
localLuaFile=require("LuaScript.txtInput")
local TextField_user=localLuaFile.CreateCustomNode()
TextField_user:ignoreContentAdaptWithSize(false)

TextField_user:setFontSize(70)
TextField_user:setPlaceHolder("点我输入用户名")
TextField_user:setString([[]])
TextField_user:setMaxLengthEnabled(false)
TextField_user:setMaxLength(0)
TextField_user:setPasswordEnabled(false)
TextField_user:setPasswordStyleText("")

TextField_user:setTouchEnabled(true)
TextField_user:setLayoutComponentEnabled(true)
TextField_user:setName("TextField_user")
TextField_user:setLocalZOrder(0)
TextField_user:setTag(33)
TextField_user:setCascadeColorEnabled(true)
TextField_user:setCascadeOpacityEnabled(true)
TextField_user:setVisible(true)
TextField_user:setAnchorPoint(0, 1)
TextField_user:setPosition(74.1243, 547.3937)
TextField_user:setScaleX(1)
TextField_user:setScaleY(1)
TextField_user:setRotation(0)
TextField_user:setRotationSkewX(0)
TextField_user:setRotationSkewY(0)
TextField_user:setOpacity(255)
TextField_user:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(TextField_user)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.1158)
layout:setPositionPercentY(0.5702)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.7813)
layout:setPercentHeight(0.0729)

layout:setSize(cc.size(500, 70))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(74.1243)
layout:setRightMargin(65.8757)
layout:setTopMargin(412.6063)
layout:setBottomMargin(477.3937)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Scene:addChild(TextField_user)

--Create TextField_pass
localLuaFile=require("LuaScript.txtInput")
local TextField_pass=localLuaFile.CreateCustomNode()
TextField_pass:ignoreContentAdaptWithSize(false)

TextField_pass:setFontSize(70)
TextField_pass:setPlaceHolder("点我输入密码")
TextField_pass:setString([[]])
TextField_pass:setMaxLengthEnabled(false)
TextField_pass:setMaxLength(0)
TextField_pass:setPasswordEnabled(true)
TextField_pass:setPasswordStyleText("*")

TextField_pass:setTouchEnabled(true)
TextField_pass:setLayoutComponentEnabled(true)
TextField_pass:setName("TextField_pass")
TextField_pass:setLocalZOrder(0)
TextField_pass:setTag(34)
TextField_pass:setCascadeColorEnabled(true)
TextField_pass:setCascadeOpacityEnabled(true)
TextField_pass:setVisible(true)
TextField_pass:setAnchorPoint(0, 1)
TextField_pass:setPosition(74.1243, 385.8609)
TextField_pass:setScaleX(1)
TextField_pass:setScaleY(1)
TextField_pass:setRotation(0)
TextField_pass:setRotationSkewX(0)
TextField_pass:setRotationSkewY(0)
TextField_pass:setOpacity(255)
TextField_pass:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(TextField_pass)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.1158)
layout:setPositionPercentY(0.4019)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.7813)
layout:setPercentHeight(0.0729)

layout:setSize(cc.size(500, 70))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(74.1243)
layout:setRightMargin(65.8757)
layout:setTopMargin(574.1391)
layout:setBottomMargin(315.8609)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Scene:addChild(TextField_pass)

--Create btnLogin
localLuaFile=require("LuaScript.button")
local btnLogin=localLuaFile.CreateCustomNode()
btnLogin:ignoreContentAdaptWithSize(false)
btnLogin:loadTextureNormal("button/btn.png",0)
btnLogin:loadTexturePressed("button/btn2.png",0)
btnLogin:loadTextureDisabled("button/btn2.png",0)
btnLogin:setTitleFontSize(40)
btnLogin:setTitleText("登录")
btnLogin:setTitleColor(cc.c3b(255, 255, 255))
btnLogin:setFlippedX(false)
btnLogin:setFlippedY(false)
btnLogin:setScale9Enabled(false)
btnLogin:setCapInsets(cc.rect(0,0,0,0))
btnLogin:setBright(true)
btnLogin:setTouchEnabled(true)
btnLogin:setLayoutComponentEnabled(true)
btnLogin:setName("btnLogin")
btnLogin:setLocalZOrder(0)
btnLogin:setTag(5)
btnLogin:setCascadeColorEnabled(true)
btnLogin:setCascadeOpacityEnabled(true)
btnLogin:setVisible(true)
btnLogin:setAnchorPoint(0.5, 0.5)
btnLogin:setPosition(295.3637, 153.2995)
btnLogin:setScaleX(1)
btnLogin:setScaleY(1)
btnLogin:setRotation(0)
btnLogin:setRotationSkewX(0)
btnLogin:setRotationSkewY(0)
btnLogin:setOpacity(255)
btnLogin:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(btnLogin)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.4615)
layout:setPositionPercentY(0.1597)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(150, 60))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(220.3637)
layout:setRightMargin(269.6363)
layout:setTopMargin(776.7005)
layout:setBottomMargin(123.2995)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Scene:addChild(btnLogin)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

