--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")
Scene:setLocalZOrder(0)

--Create Image_4
localLuaFile=require("LuaScript.image")
local Image_4=localLuaFile.CreateCustomNode()
Image_4:ignoreContentAdaptWithSize(false)
Image_4:loadTexture("image/scenebg.png",0)

Image_4:setFlippedX(false)
Image_4:setFlippedY(false)

Image_4:setScale9Enabled(false)
Image_4:setCapInsets(cc.rect(0,0,0,0))
Image_4:setTouchEnabled(false)
Image_4:setLayoutComponentEnabled(true)
Image_4:setName("Image_4")
Image_4:setLocalZOrder(0)
Image_4:setTag(18)
Image_4:setCascadeColorEnabled(true)
Image_4:setCascadeOpacityEnabled(true)
Image_4:setVisible(true)
Image_4:setAnchorPoint(0, 0)
Image_4:setPosition(0, 0)
Image_4:setScaleX(1)
Image_4:setScaleY(1)
Image_4:setRotation(0)
Image_4:setRotationSkewX(0)
Image_4:setRotationSkewY(0)
Image_4:setOpacity(255)
Image_4:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Image_4)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(640, 960))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(0)
layout:setRightMargin(0)
layout:setTopMargin(0)
layout:setBottomMargin(0)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Scene:addChild(Image_4)

--Create Text_desc
local Text_desc = ccui.Text:create()
Text_desc:ignoreContentAdaptWithSize(true)
Text_desc:setTextAreaSize(cc.size(0, 0))
Text_desc:setFontName("resource/Msyh.ttf")
Text_desc:setFontSize(36)
Text_desc:setString([[消息通知                            
消息通知                 
消息通知                 
消息通知                 
消息通知                 
消息通知                 
消息通知                 
消息通知                 
消息通知                 
消息通知                 

消息通知                 ]])
Text_desc:setTextHorizontalAlignment(0)
Text_desc:setTextVerticalAlignment(0)
Text_desc:setTouchScaleChangeEnabled(false)
Text_desc:setFlippedX(false)
Text_desc:setFlippedY(false)
Text_desc:setTouchEnabled(false)
Text_desc:setLayoutComponentEnabled(true)
Text_desc:setName("Text_desc")
Text_desc:setLocalZOrder(0)
Text_desc:setTag(128)
Text_desc:setCascadeColorEnabled(true)
Text_desc:setCascadeOpacityEnabled(true)
Text_desc:setVisible(true)
Text_desc:setAnchorPoint(0.5, 0.5)
Text_desc:setPosition(308.0342, 414.7594)
Text_desc:setScaleX(1)
Text_desc:setScaleY(1)
Text_desc:setRotation(0)
Text_desc:setRotationSkewX(0)
Text_desc:setRotationSkewY(0)
Text_desc:setOpacity(255)
Text_desc:setColor(cc.c3b(30, 144, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.4813)
layout:setPositionPercentY(0.432)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(452, 576))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(82.0342)
layout:setRightMargin(105.9658)
layout:setTopMargin(257.2406)
layout:setBottomMargin(126.7594)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Scene:addChild(Text_desc)

--Create btnClose
localLuaFile=require("LuaScript.button")
local btnClose=localLuaFile.CreateCustomNode()
btnClose:ignoreContentAdaptWithSize(false)
btnClose:loadTextureNormal("button/btn.png",0)
btnClose:loadTexturePressed("button/btn2.png",0)
btnClose:loadTextureDisabled("button/btn2.png",0)
btnClose:setTitleFontSize(40)
btnClose:setTitleText("关闭")
btnClose:setTitleColor(cc.c3b(255, 255, 255))
btnClose:setFlippedX(false)
btnClose:setFlippedY(false)
btnClose:setScale9Enabled(false)
btnClose:setCapInsets(cc.rect(0,0,0,0))
btnClose:setBright(true)
btnClose:setTouchEnabled(true)
btnClose:setLayoutComponentEnabled(true)
btnClose:setName("btnClose")
btnClose:setLocalZOrder(0)
btnClose:setTag(19)
btnClose:setCascadeColorEnabled(true)
btnClose:setCascadeOpacityEnabled(true)
btnClose:setVisible(true)
btnClose:setAnchorPoint(0.5, 0.5)
btnClose:setPosition(316.1598, 861.2765)
btnClose:setScaleX(1)
btnClose:setScaleY(1)
btnClose:setRotation(0)
btnClose:setRotationSkewX(0)
btnClose:setRotationSkewY(0)
btnClose:setOpacity(255)
btnClose:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(btnClose)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.494)
layout:setPositionPercentY(0.8972)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(150, 60))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(241.1598)
layout:setRightMargin(248.8402)
layout:setTopMargin(68.7235)
layout:setBottomMargin(831.2765)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Scene:addChild(btnClose)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

